{% set name = "pythx" %}
{% set version = "1.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pythx-{{ version }}.tar.gz
  sha256: e2346d47c984f577636eef79f0c860eb091f3198861851c537443792a64643fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6,<4
  run:
    - inflection ==0.5.1
    - mythx-models ==2.0.1
    - pyjwt ==1.7.1
    - python >=3.6,<4
    - python-dateutil ==2.8.1
    - requests ==2.25.0

test:
  imports:
    - pythx
    - pythx.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmuhs/pythx
  summary: A Python library for the MythX platform
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
